### ISSUE TITLE
Schema "path" parameters are not validated

### ISSUE THREAD

**Issue by shadowhand** [eleven-labs/api-validator#15]
Given the following schema:

```yml
paths:
  /users/{id}:
    get:
      summary: view a user
      operationId: user.view
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: user id
        required: true
        type: integer
        minimum: 1
```

The `{id}` parameter should be validated against the request path.
